---
- name: restart lxd-bridge
  service: name=lxd-bridge state=restarted
  when: >
    ansible_distribution_release == 'xenial' and
    (ansible_virtualization_type is not defined or not (ansible_virtualization_type == "lxc"))
