---

k3s_version: v1.19.3+k3s3

k3s_binary_map:
  "x86_64": "k3s"
  "aarch64": "k3s-arm64"
  "aarch": "k3s-arm64"
  "armhf": "k3s-armhf"
  "armv7l": "k3s-armhf"

k3s_binary_name: "{{ k3s_binary_map[ansible_architecture] }}"

k3s_checksum_map:
  "k3s": "sha256:ad296fb03eb31334eb88ba4c54690145d3f343bde17a1331803093c544025b4a"
  "k3s-arm64": "sha256:79345a9534678261e77a78af5db9cfe5c9c44bddffddd504fe3eb5bb921df313"
  "k3s-arm": "sha256:f9d6c573489e8cf24b7e30041c8fa51fff1b4fcccc7a6a2b8133d54666a41d6a"

k3s_binary_checksum: "{{ k3s_checksum_map[k3s_binary_name] }}"

systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['k3s_master'][0]]['ansible_host'] | default(groups['k3s_master'][0]) }}"
extra_server_args: ""
extra_agent_args: ""
