---
## don't reboot system if needed
lxd_noreboot: true

lxd_with_zfs_backend: false
lxd_zfs_size: 25GB
lxd_storage_name: myzfspool

# if storage dir and else
lxd_init_file_test: /var/lib/lxd/networks/lxdfan0
# if storage zfs only
#lxd_init_file_test: "/var/lib/lxd/disks/{{ lxd_storage_name }}.img"

lxd_fanconf_use_fan: false
#lxd_fanconf_fan: "lxdfan0"
lxd_fanconf_fan: ""
lxd_fanconf_underlay_subnet: "auto"

lxd_bridgeconf_use_bridge: false
#lxd_bridgeconf_bridge: "lxdbr0"
lxd_bridgeconf_bridge: ""
#lxd_bridgeconf_ipv4_addr: "10.0.51.1"
#lxd_bridgeconf_ipv4_netmask: "255.255.255.0"
#lxd_bridgeconf_ipv4_network: "10.0.51.1/24"
#lxd_bridgeconf_ipv4_dhcp_range: "10.0.51.2-10.0.51.254"
#lxd_bridgeconf_ipv4_dhcp_max: 253
lxd_bridgeconf_ipv4_nat: true
lxd_bridgeconf_ipv6_addr: "none"
lxd_bridgeconf_ipv6_dhcp: false
lxd_bridgeconf_ipv6_dhcp_range: ""
lxd_bridgeconf_ipv6_proxy: false

lxd_dnsmasq_conf: false
lxd_dnsmasq_staticips: []

lxd_force_ubuntu_backports: false

## https://github.com/lxc/lxd/issues/1229, increase required if using nesting
lxd_subid_start: 100000
lxd_subid_range: 65536
#lxd_subid_range: 1065536
