---

- name: Enable cgroup via boot commandline if not already enabled for Ubuntu on ARM
  lineinfile:
    path: /boot/firmware/cmdline.txt
    backrefs: true
    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
  when:
    - ansible_distribution == 'Ubuntu'
    - ( ansible_facts.architecture is search("arm") or
        ansible_facts.architecture is search("aarch64") )
  register: enabled_cgroup

- name: Reboot to enable cgroups for Ubuntu on ARM
  reboot:
  when:
    - enabled_cgroup is changed
    - ansible_distribution == 'Ubuntu'
    - ( ansible_facts.architecture is search("arm") or
        ansible_facts.architecture is search("aarch64") )
