---
- name: 'validate variable : cloudflared_enabled'
  assert:
    that:
      - cloudflared_enabled | type_debug == 'bool'
    fail_msg:
      - "Variable 'cloudflared_enabled' should be of type 'bool'"
      - 'Type is: {{ cloudflared_enabled | type_debug }}'
      - "Value is: {{ cloudflared_enabled | default('undefined') }}"

- name: 'validate variable : cloudflared_kube_api_server_dns'
  assert:
    that:
      - cloudflared_kube_api_server_dns | type_debug == 'AnsibleUnicode'
      - cloudflared_kube_api_server_dns | length > 0
    fail_msg:
      - "Variable 'cloudflared_kube_api_server_dns' should be of type AnsibleUnicode (string)"
      - 'Type is: {{ cloudflared_kube_api_server_dns | type_debug }}'
      - "Value is: {{ cloudflared_kube_api_server_dns | default('undefined') }}"
  when:
    - cloudflared_enabled

- name: 'validate variable : cloudflared_version'
  assert:
    that:
      - cloudflared_version | type_debug == 'AnsibleUnicode'
      - cloudflared_version | length > 0
    fail_msg:
      - "Variable 'cloudflared_version' should be of type AnsibleUnicode (string)"
      - 'Type is: {{ cloudflared_version | type_debug }}'
      - "Value is: {{ cloudflared_version | default('undefined') }}"
  when:
    - cloudflared_enabled
